services:
  goofyn-main:
    image: rpdjf/goofyn:latest
    container_name: goofyn
    depends_on:
      - goofyn-mongodb
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DB: goofyn
      MONGO_URI: mongodb://goofyn-mongodb:27017
      #SCRIPT: firestore2mongo.js # only if using firestore2mongo script
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.env:/usr/src/app/.env # can be setup in environment variables instead
      #- ./firebase-key.json:/usr/src/app/config/firebase-key.json # only if using firestore2mongo script
    restart: always
  goofyn-mongodb:
    image: mongo:latest
    container_name: goofyn-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: goofyn
      MONGO_PORT: 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo-data:/data/db