services:
  discord-goofyn:
    container_name: discord-goofyn
    image: rpdjf/discord-goofyn:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.env:/usr/src/app/.env
      - ./firebase-key.json:/usr/src/app/config/firebase-key.json
    restart: always