services:
  discord-goofyn:
    container_name: discord-goofyn
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.env:/usr/src/app/.env
      - ./firebase-key.json:/usr/src/app/config/firebase-key.json
    restart: always