services:
  discord-goofyn:
    container_name: discord-goofyn
    image: rpdjf/discord-goofyn:latest
    volumes:
      - ./.env:/usr/src/app/.env
      - ./firebase-key.json:/usr/src/app/config/firebase-key.json
    environment:
      - TZ=Europe/Zurich
    restart: always